listen_addresses = '*'
port = 9999
backend_hostname0 = '10.0.70.164'
backend_port0 = 5432
backend_weight0 = 1

backend_hostname1 = '10.0.70.224'
backend_port1 = 5432
backend_weight1 = 1

backend_hostname2 = '10.0.70.81'
backend_port2 = 5432
backend_weight2 = 1

backend_hostname3 = '10.0.70.50'
backend_port3 = 5432
backend_weight3 = 1

backend_hostname4 = '10.0.70.51'
backend_port4 = 5432
backend_weight4 = 1

backend_hostname5 = '10.0.70.52'
backend_port5 = 5432
backend_weight5 = 1

backend_hostname6 = '10.0.70.53'
backend_port6 = 5432
backend_weight6 = 1

backend_hostname7 = '10.0.70.54'
backend_port7 = 5432
backend_weight7 = 1

backend_hostname8 = '10.0.70.80'
backend_port8 = 5432
backend_weight8 = 1

backend_hostname9 = '10.0.70.82'
backend_port9 = 5432
backend_weight9 = 1

backend_hostname10 = '10.0.70.84'
backend_port10 = 5432
backend_weight10 = 1

backend_hostname11 = '10.0.70.85'
backend_port11 = 5432
backend_weight11 = 1

backend_hostname12 = '10.0.70.95'
backend_port12 = 5432
backend_weight12 = 1

backend_hostname13 = '10.0.70.249'
backend_port13 = 5432
backend_weight13 = 1

backend_hostname14 = '10.0.70.149'
backend_port14 = 5432
backend_weight14 = 1
